### ISSUE TITLE
co-wechat-oauth@2.0.1版本babel无法运行

### ISSUE THREAD

**Issue by dcboy** [node-webot/co-wechat-oauth#7]
hi,安装了co-wechat-oauth@2.0.1后es7下面编译错误
`node_modules/co-wechat-oauth/lib/oauth.js:49
    this.getToken = getToken || async function (openid) {
                                      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/D/project/yopoint/project/yp-service-consumer/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/D/project/yopoint/project/yp-service-consumer/src/modules/consumer/services/wx.js:7:1)
    at Module._compile (module.js:556:32)
    at loader (/Volumes/D/project/yopoint/project/yp-service-consumer/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/D/project/yopoint/project/yp-service-consumer/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Seneca.useAsync (/Volumes/D/project/yopoint/project/yp-service-consumer/node_modules/seneca-extended/src/utils.js:132:50)
    at /Volumes/D/project/yopoint/project/yp-service-consumer/src/app.js:42:20
    at arrayEach (/Volumes/D/project/yopoint/project/yp-service-consumer/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Volumes/D/project/yopoint/project/yp-service-consumer/node_modules/lodash/lodash.js:9359:14)`

**Comment by JacksonTian** [comment]
如果要用2.x 请升级能直接运行async functions 的版本
